//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGS.BusinessLogic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SGS.BusinessLogic.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe otro usuario con el mismo Cuit ingresado.
        /// </summary>
        internal static string DuplicateCuit {
            get {
                return ResourceManager.GetString("DuplicateCuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe otro venue con la misma denominación ingresado.
        /// </summary>
        internal static string DuplicateDenominacion {
            get {
                return ResourceManager.GetString("DuplicateDenominacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe otro usuario con el mismo documento ingresado.
        /// </summary>
        internal static string DuplicateDocumento {
            get {
                return ResourceManager.GetString("DuplicateDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe otro usuario con el mismo email ingresado.
        /// </summary>
        internal static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe otro usuario con el mismo nick ingresado.
        /// </summary>
        internal static string DuplicateNick {
            get {
                return ResourceManager.GetString("DuplicateNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no posee una dirección de correo asociada para poder enviar las nuevas credenciales.
        /// </summary>
        internal static string EmailEmpty {
            get {
                return ResourceManager.GetString("EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente inválido.
        /// </summary>
        internal static string InvalidCliente {
            get {
                return ResourceManager.GetString("InvalidCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal técnico inválido.
        /// </summary>
        internal static string InvalidPersonalTecnico {
            get {
                return ResourceManager.GetString("InvalidPersonalTecnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea inválida.
        /// </summary>
        internal static string InvalidTarea {
            get {
                return ResourceManager.GetString("InvalidTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario inválido.
        /// </summary>
        internal static string InvalidUsuario {
            get {
                return ResourceManager.GetString("InvalidUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue inválido.
        /// </summary>
        internal static string InvalidVenue {
            get {
                return ResourceManager.GetString("InvalidVenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGS - Nuevas credenciales.
        /// </summary>
        internal static string NewPasswordSubject {
            get {
                return ResourceManager.GetString("NewPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGS- Nuevo usuario.
        /// </summary>
        internal static string NewUserSubject {
            get {
                return ResourceManager.GetString("NewUserSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el apellido.
        /// </summary>
        internal static string RequiredApellido {
            get {
                return ResourceManager.GetString("RequiredApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el cargo.
        /// </summary>
        internal static string RequiredCargo {
            get {
                return ResourceManager.GetString("RequiredCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione la categoría.
        /// </summary>
        internal static string RequiredCategoria {
            get {
                return ResourceManager.GetString("RequiredCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el contacto de referencia.
        /// </summary>
        internal static string RequiredContactoReferencia {
            get {
                return ResourceManager.GetString("RequiredContactoReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el Cuit.
        /// </summary>
        internal static string RequiredCuit {
            get {
                return ResourceManager.GetString("RequiredCuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese la denominación.
        /// </summary>
        internal static string RequiredDenominacion {
            get {
                return ResourceManager.GetString("RequiredDenominacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese la dirección principal.
        /// </summary>
        internal static string RequiredDireccionPrincipal {
            get {
                return ResourceManager.GetString("RequiredDireccionPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el email.
        /// </summary>
        internal static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el estado de la tarea.
        /// </summary>
        internal static string RequiredEstadoTarea {
            get {
                return ResourceManager.GetString("RequiredEstadoTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el nick.
        /// </summary>
        internal static string RequiredNick {
            get {
                return ResourceManager.GetString("RequiredNick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el nombre.
        /// </summary>
        internal static string RequiredNombre {
            get {
                return ResourceManager.GetString("RequiredNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione la prioridad.
        /// </summary>
        internal static string RequiredPrioridad {
            get {
                return ResourceManager.GetString("RequiredPrioridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese la razón social.
        /// </summary>
        internal static string RequiredRazonSocial {
            get {
                return ResourceManager.GetString("RequiredRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el teléfono.
        /// </summary>
        internal static string RequiredTelefono {
            get {
                return ResourceManager.GetString("RequiredTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el tipo de establecimiento.
        /// </summary>
        internal static string RequiredTipoEstablecimiento {
            get {
                return ResourceManager.GetString("RequiredTipoEstablecimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el tipo de tarea.
        /// </summary>
        internal static string RequiredTipoTarea {
            get {
                return ResourceManager.GetString("RequiredTipoTarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el título.
        /// </summary>
        internal static string RequiredTitulo {
            get {
                return ResourceManager.GetString("RequiredTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el usuario.
        /// </summary>
        internal static string RequiredUsuario {
            get {
                return ResourceManager.GetString("RequiredUsuario", resourceCulture);
            }
        }
    }
}
